org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_api_version=0.146.1+26.1.2

# Mod Properties
mod_id=blockbox
mod_name=The Block Box
mod_license=https://github.com/vectorwing/BlockBox/blob/1.21.1/LICENSE
mod_version=26.06.16-26.1-fabric
mod_group_id=com.axperty.blockbox
mod_authors=Axperty, vectorwing
mod_description=A collection of building blocks, furniture and decorations!
maven_group=com.axperty
archives_base_name=blockbox